"""Build and recover assertions in native Appian RuleTestConfig XML."""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from datetime import date, datetime
from typing import TypeAlias

from lxml import etree

from appian_sentinel.models.test_case import AppianAssertionType

APPIAN_NS = "http://www.appian.com/ae/types/2009"
XSD_NS = "http://www.w3.org/2001/XMLSchema"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"

ASSERTION_ENUMS: dict[AppianAssertionType, str] = {
    AppianAssertionType.OUTPUT_EQUALS: "OUTPUT_EQUALS",
    AppianAssertionType.EXPRESSION: "EXPRESSION",
}

# ponytail: scalar expected values only; add proven Appian complex types as needed.
ScalarValue: TypeAlias = str | bool | int | float | date | datetime | None


@dataclass(frozen=True, slots=True)
class NativeAssertion:
    """One assertion recovered from a RuleTestConfig element."""

    assertion_type: AppianAssertionType
    expected: ScalarValue = None
    assertion_expression: str = ""
    expected_xsi_type: str = ""


def find_native_test_cases(root: etree._Element) -> list[etree._Element]:
    """Return RuleTestConfig entries from a parsed rule or interface export."""
    return list(root.xpath(
        "//*[local-name()='typedValue']"
        "[*[local-name()='type']/*[local-name()='name']"
        "[normalize-space(.)='RuleTestConfig?list']]"
        "/*[local-name()='value']/*[local-name()='el']"
    ))


def build_native_assertion(
    assertion_type: AppianAssertionType | str,
    *,
    expected: ScalarValue = None,
    assertion_expression: str = "",
) -> etree._Element:
    """Build an Appian-namespaced ``assertions`` element."""
    mode = AppianAssertionType(assertion_type)
    node = etree.Element(etree.QName(APPIAN_NS, "assertions"))

    if mode is AppianAssertionType.COMPLETES_WITHOUT_ERROR:
        if expected is not None or assertion_expression.strip():
            raise ValueError("completes_without_error cannot define an assertion value")
        node.set(etree.QName(XSI_NS, "nil"), "true")
        return node

    assertion_enum = etree.SubElement(node, etree.QName(APPIAN_NS, "type"))
    assertion_enum.text = ASSERTION_ENUMS[mode]
    value = etree.SubElement(node, etree.QName(APPIAN_NS, "value"))

    if mode is AppianAssertionType.EXPRESSION:
        expression = assertion_expression.strip()
        if not expression or "test!output" not in expression.casefold():
            raise ValueError("expression assertions must reference test!output")
        value.set(etree.QName(XSI_NS, "type"), "a:Expression")
        value.text = expression
        return node

    if assertion_expression.strip():
        raise ValueError("assertion_expression requires assertion_type='expression'")
    _set_typed_scalar(value, expected)
    return node


def set_native_assertion(
    test_case: etree._Element,
    assertion_type: AppianAssertionType | str,
    *,
    expected: ScalarValue = None,
    assertion_expression: str = "",
) -> etree._Element:
    """Replace a RuleTestConfig entry's assertion without an assertion template."""
    assertion = build_native_assertion(
        assertion_type,
        expected=expected,
        assertion_expression=assertion_expression,
    )
    existing = _direct_children(test_case, "assertions")
    if existing:
        position = test_case.index(existing[0])
        test_case.remove(existing[0])
        test_case.insert(position, assertion)
    else:
        test_case.append(assertion)
    return assertion


def clone_test_case_with_assertion(
    template: etree._Element,
    name: str,
    assertion_type: AppianAssertionType | str,
    *,
    expected: ScalarValue = None,
    assertion_expression: str = "",
) -> etree._Element:
    """Clone one real RuleTestConfig entry and replace only its assertion."""
    test_case = deepcopy(template)
    names = _direct_children(test_case, "name")
    if not names:
        raise ValueError("RuleTestConfig entry is missing name")
    names[0].text = name
    set_native_assertion(
        test_case,
        assertion_type,
        expected=expected,
        assertion_expression=assertion_expression,
    )
    return test_case


def extract_native_assertion(test_case: etree._Element) -> NativeAssertion:
    """Recover an assertion generated by this module or a native nil assertion."""
    assertions = _direct_children(test_case, "assertions")
    if not assertions:
        return NativeAssertion(AppianAssertionType.COMPLETES_WITHOUT_ERROR)
    node = assertions[0]
    if node.get(etree.QName(XSI_NS, "nil")) == "true":
        return NativeAssertion(AppianAssertionType.COMPLETES_WITHOUT_ERROR)

    enum_nodes = _direct_children(node, "type")
    value_nodes = _direct_children(node, "value")
    if not enum_nodes or not value_nodes:
        raise ValueError("assertions element is missing type or value")
    enum_value = (enum_nodes[0].text or "").strip()
    reverse_enums = {value: key for key, value in ASSERTION_ENUMS.items()}
    try:
        mode = reverse_enums[enum_value]
    except KeyError as exc:
        raise ValueError(f"unsupported Appian assertion enum: {enum_value}") from exc

    value = value_nodes[0]
    xsi_type = value.get(etree.QName(XSI_NS, "type"), "")
    if mode is AppianAssertionType.EXPRESSION:
        expression = value.text or ""
        if "test!output" not in expression.casefold():
            raise ValueError("expression assertions must reference test!output")
        return NativeAssertion(
            assertion_type=mode,
            assertion_expression=expression,
            expected_xsi_type=xsi_type,
        )
    return NativeAssertion(
        assertion_type=mode,
        expected=_read_typed_scalar(value, xsi_type),
        expected_xsi_type=xsi_type,
    )


def _direct_children(node: etree._Element, local_name: str) -> list[etree._Element]:
    return list(node.xpath(f"./*[local-name()='{local_name}']"))


def _set_typed_scalar(node: etree._Element, value: ScalarValue) -> None:
    if value is None:
        node.set(etree.QName(XSI_NS, "nil"), "true")
        return
    if isinstance(value, bool):
        xsi_type, text = "xsd:boolean", str(value).lower()
    elif isinstance(value, int):
        xsi_type, text = "xsd:int", str(value)
    elif isinstance(value, float):
        xsi_type, text = "xsd:double", repr(value)
    elif isinstance(value, datetime):
        xsi_type, text = "xsd:dateTime", value.isoformat()
    elif isinstance(value, date):
        xsi_type, text = "xsd:date", value.isoformat()
    elif isinstance(value, str):
        xsi_type, text = "xsd:string", value
    else:
        raise TypeError(f"unsupported expected value type: {type(value).__name__}")
    node.set(etree.QName(XSI_NS, "type"), xsi_type)
    node.text = text


def _read_typed_scalar(node: etree._Element, xsi_type: str) -> ScalarValue:
    if node.get(etree.QName(XSI_NS, "nil")) == "true":
        return None
    text = node.text or ""
    if xsi_type == "xsd:boolean":
        return text.strip().casefold() == "true"
    if xsi_type == "xsd:int":
        return int(text)
    if xsi_type == "xsd:double":
        return float(text)
    if xsi_type == "xsd:dateTime":
        return datetime.fromisoformat(text)
    if xsi_type == "xsd:date":
        return date.fromisoformat(text)
    if xsi_type == "xsd:string":
        return text
    raise ValueError(f"unsupported expected xsi:type: {xsi_type}")
